version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    # networks:
    #   - node-network

  flask_app:
    depends_on:
      - mongodb
    container_name: flask-app
    build: .
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - "8003:8003"
      - "4431:443"
    restart: always

  reverse_proxy:
    depends_on:
      - flask_app
    container_name: reverse-proxy
    hostname: reverse
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_data:/etc/ssl/private

volumes:
  dbdata6: {}
  nginx_data: {}
# networks:
#   node-network:
#     external: true

