password: ENC[AES256_GCM,data:2cWybA==,iv:nqUJQNo4ViZ5BmixKw7Gkh8tzDEI7zY2GgbTn4k0k4s=,tag:TI032dvxH8uCb3PEPtkpCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-17T12:05:45Z"
    mac: ENC[AES256_GCM,data:j4dYhKRh8qKgOMAA//odFpSb+viMrIRxK6FRbSMP5kcf9fPvlfbC5H8Ld5cKc6iTSacmcAup6efg/81Z70IKCmZWsGJ6+BJ/7kEp3h+chU7zbb0qcSYv/CJ2ooyu2JqnZnhcbEqJeGxxNQ+mTqnnAWWWIw0vgpaHpmJP4ZwZqkA=,iv:X2uvgH2BuHTJwnyXNfw0B59nE77qyYcE7MWkQhecCeU=,tag:P8xTmjoaeh5FiKG5tpWabQ==,type:str]
    pgp:
        - created_at: "2024-06-17T12:05:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+Bo3WIBzra7ARAAt4djvKCqBiL78h31Il56zYL3+GDY+ES2qdCoGmLrpF/1
            q3PQ16oV2lu4SEFZXpG6R5RNsbZeS+qCu9wSfYb2mIsq9nS8pM8vDyiZQltn70Y/
            mx1jc5Mt0m1udVFdqDjizDAS3erVNdoR02ZcmjKZwf5OMh8umdd0G0oKlVaJuP2P
            diH01IEwpDfFGPHazSaru9VKN1pM80PIqS+N2MnEK3yY1rIwYJl+7wwwyWQO6vOy
            KinYt6DfVfCwK0eANj2I4/AyCq1LJ9sU2/gcnzeLdVDHhfp2x3Zg+qq9lpWnOFl2
            8N0q7lMr2dXC3V9f4LOpz9vXupZ0EBtg+xCddKkXnx3a4D+WVz3d6EF2xF1n+nko
            vauEb351Az31OxoML9sXDwYn8rSZuBRav+uYF4NI7nnNhA6HVmXlrRT9a58wtY+z
            aKukZfpTyKBnW5rbFIZ2yVUiFaLxA/TDHgmBIvXFLU2CbuNcQbAr9LKmmGgfi+bh
            MkhHVXeBgvIkRZM7lpThzh1wAMy8QJPulWchzrq0tBZ3MkrV4fUxwxd9kEAXli1x
            Xq6PAgLaLaCvoLo8OKDwt9oAhDTRSJc+W6KyLx4t7wz5OiPl/Pvg8MlDSH9VottB
            ug9ztHpnCo3Vu3HhONTvYNiC4uADSGdfJn1xlCENvdHY8mJz24HhkjqiDWw60KzS
            XgEzYtv2VV7T+cVgAkufHFjbktpOQmPqiwU4/xAF5QzMS+wDNYc8zXZ6EPRlFrbP
            M0brQjkSM+7/T3nZzqSmmBbcnmzawDgHBewzFevMluNgL0m7LEQnL/BrfGvfGMU=
            =A8lV
            -----END PGP MESSAGE-----
          fp: 7F17DFDA88D1D1BEC1385E20649458A9140B279A
    unencrypted_suffix: _unencrypted
    version: 3.7.3
