apiVersion: batch/v1
kind: Job
metadata:
  name: job-hook-preinstall
  annotations:
    "helm.sh/hook": "pre-install"

spec:
  template:
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: pre-install
          image: busybox
          command: ["sh", "-c", "echo pre-install Job Pod is Running ; sleep 5"]

      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
      activeDeadlineSeconds: 60
