apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.49.3
    path: /data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
