name: Build, Test, and Deploy WeatherApp

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to DockerHub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }} 

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USER }}/weatherapp:latest .
        docker tag ${{ secrets.DOCKERHUB_USER }}/weatherapp:latest ${{ secrets.DOCKERHUB_USER }}/weatherapp:${{ github.sha }}

    # # Test the Docker image
    # - name: Run container to test
    #   run: |
    #     docker run --rm -d --name weatherapp-test -p 80:5000 ${{ secrets.DOCKERHUB_USER }}/weatherapp:latest
    #     # Wait for a few seconds for the app to start
    #     sleep 10
    #     # Check if the app is running by making a request to the health endpoint or main page
    #     curl --fail http://localhost:80/health || (docker logs weatherapp-test && exit 1)
    #     docker stop weatherapp-test

    # Push Docker image to DockerHub
    - name: Push Docker image to DockerHub
      run: |
        docker push ${{ secrets.DOCKERHUB_USER }}/weatherapp:latest
        docker push ${{ secrets.DOCKERHUB_USER }}/weatherapp:${{ github.sha }}

  update-k8s-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
              
      
    steps:
    # Checkout the Kubernetes manifest repository
    - name: Setup yq
      uses: vegardit/gha-setup-yq@v1
    
    - name: Checkout Kubernetes manifest repository
      uses: actions/checkout@v3
      with:
        repository: Zivgl66/k8s-weatherapp 
        token: ${{ secrets.GH_TOKEN }}
        path: k8s-manifests  

        
    # Update the Kubernetes deployment manifest
    - name: Update Kubernetes deployment manifest
      run: |
        # Replace the image tag in the Kubernetes deployment manifest
        # yq -i -y '.spec.template.spec.containers[0].image = "${{ secrets.DOCKERHUB_USER }}/weatherapp:${{ github.sha }}"' k8s-manifests/deployment.yaml
        yq eval '.spec.template.spec.containers[0].image = "${{ secrets.DOCKERHUB_USERNAME }}/weatherapp:${{ github.sha }}"' -i k8s-manifests/deployment.yaml

    - name: Print deployment manifest after update
      run: cat k8s-manifests/deployment.yaml

    # Commit and push changes
    - name: Commit and push changes
      run: |
        cd k8s-manifests
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add deployment.yaml 
        git commit -m "Update deployment image to ${{ secrets.DOCKERHUB_USERNAME }}/weatherapp:${{ github.sha }}"
        git push origin main
